### ISSUE TITLE
Add some form of indicator when the simulator is running

### ISSUE THREAD

**Issue by acrosman** [acrosman/simple-project-estimates#3]
When you click "Run Simulation" if the number of iterations is very large it takes awhile, but there is nothing to indicate that it has responded.  Some degree of greying out the button and showing a spinner of some kind would be helpful.

**Comment by ccmetz** [comment]
Hey @acrosman , I'd love to work on this one. Can you assign it to me?

**Comment by acrosman** [comment]
Huh, wow that's an old bit of code.  The double slash tells the browser to load the URL with the same protocol as the page itself (used to be common to ensure you didn't get errors when using both HTTP and HTTPS). It causes it to break when you load the file directly, but if you via a web server it'll work just fine, but if you load it from a file it will not.  

I've also add #4 to update to a more recent version of jQuery.

**Comment by ccmetz** [comment]
PR is ready for review: #6
